const mongoose = require("mongoose");
const variable = require("../../variable")

const otpSchema = new mongoose.Schema({ // Otp._id will give id of any particular otp
    
    signupId: {
        // Profile._id of the Profile for which otp value is generated
        type: mongoose.Types.ObjectId,
        ref: "Signup",
        required: true
    },
    otpValue: {
        // The otp value that will be used to verify identity of the user
        type: String,
        required: true
    },
    for: {
        // To verify that this otp is for forgotPassword(0) or emailVerification(1) or mobileVerification(2)
        type: Number,
        required: true,
    },
    // createdAt: {
    //     // Time at which OTP expires
    //     type: Date,
    //     required: true,
    //     default: Date.now(),
    // },
    expiryTime: {
        type: Number,
        required: true
    }
},{timestamps: true})
// createdAt value is automatically generated by timestamp
// otpSchema.index({createdAt: 1},{expireAfterSeconds: 1000});

module.exports = mongoose.model("Otp",otpSchema);